name: Multi-arch test
on: push

jobs:
  arch-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-dist-list.outputs.dist-list }}
    steps:
      - uses: actions/setup-go@v3
      - id: get-dist-list
        run: |
          echo "::set-output name=dist-list::$(
            go tool dist list -json \
            | jq -c '{
                dist: [
                  .[]
                  | select(.GOOS=="linux")
                  | select(.GOARCH!="mips")
                  | select(.GOARCH!="mipsle")
                  | select(.GOARCH!="ppc64")
                ]
              }'
          )"

  test:
    runs-on: ubuntu-latest
    needs: arch-list
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.arch-list.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: docker/setup-qemu-action@v2
      - name: "Test binary for target arch: ${{ matrix.dist.GOARCH }}"
        run: go test -v .
        env:
          GOOS: ${{ matrix.dist.GOOS }}
          GOARCH: ${{ matrix.dist.GOARCH }}
      - name: "Build binary for target arch: ${{ matrix.dist.GOARCH }}"
        run: |
          go build -o hello .
          file hello
        env:
          GOOS: ${{ matrix.dist.GOOS }}
          GOARCH: ${{ matrix.dist.GOARCH }}
      - name: Run the binary
        run: ./hello
